name = "expense-api"
main = "src/index.ts"
compatibility_date = "2024-10-29"
compatibility_flags = ["nodejs_compat"]


# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
